### ISSUE TITLE
[dependencies] update checklist

### ISSUE THREAD

**Issue by tuogeniy** [Atlantis-Lab/nestjs#139]
### Список зависимостей на обновление

- [ ] https://github.com/Atlantis-Lab/nestjs/pull/135
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/134
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/133
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/132
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/131
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/130
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/129
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/123
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/122
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/93
- [ ] https://github.com/Atlantis-Lab/nestjs/pull/76

**Comment by TorinAsakura** [comment]
@tuogeniy чо ты меня заасайнил? Делай и отмечай по ходу дела
